### ISSUE TITLE
mockOther replaceWith type should be any

### ISSUE THREAD

**Issue by HopefulLlama** [EmandM/ts-mock-imports#1]
Currently, `mockOther` has a type definition as follows: 

```
static mockOther<T extends IModule, K extends keyof T>(module: {
        [importName: string]: T[K];
    } | T, importName?: K, replaceWith?: T[K]): OtherManager<T[K]>;
```

The important part being: `replaceWith?: T[K]`. This can be prohibitive when trying to mock large APIs, in which you wish to only mock a few properties.

The reason is that requiring type `T[K]` means that your mock object must have all the properties defined, even if you wish to only test or mock a few of these properties.

For this reason, I believe the return type would be better served to be `any`. This enables the developer to specify the shape of the mock object as they like.

**Comment by EmandM** [comment]
Would `Partial<T[K]>` suit your needs? It's important to ensure top level imports retain their type safety, so that issues can be caught by the compiler rather than at run time.

**Comment by HopefulLlama** [comment]
`Partial<T[K]>` could work, yeah

**Comment by EmandM** [comment]
The fix for this is in the latest version 🎉
