### ISSUE TITLE
Possible to mock aws-sdk?

### ISSUE THREAD

**Issue by lsanders** [EmandM/ts-mock-imports#11]
I know there's an aws-sdk-mock package, but I like that ts-mock-imports is generic. That said, I'm having trouble mocking it. There's so may different ways to import which could be where I'm getting tripped up. 

Just wondering if others have successfully mocked aws-sdk with this lib?

**Comment by EmandM** [comment]
You can totally use this library to mock out the AWS sdk. I'm happy to provide help if you have more information about what you are trying to achieve and what is not working.

**Comment by lsanders** [comment]
Thanks for the replay @EmandM! Just knowing it's possible helps.

As an example, I'm trying to mock StepFunctions:

production code
``` 
import * as StepFunctions from 'aws-sdk/clients/stepfunctions';

const step = new StepFunctions({ region: config.aws_region });
```
tests
```
import * as stepFunctionModule from 'aws-sdk/clients/stepfunctions';

describe('', function() {
   let stepFunctionMock;
   before(function () {
     stepFunctionMock = Import.mockClass(stepFunctionModule);
```   

I've tried various forms of  `Import.mockClass`, but mostly getting 
```

message:"Cannot read property 'prototype' of undefined"
stack:"TypeError: Cannot read property 'prototype' of undefined\n    at MockManager.getAllFunctionNames 
``` 

aws-sdk/clients/stepfunctions imports several internal libs and declares:
```
declare class StepFunctions extends Service {
....
export = StepFunctions;
```
Any guidance would be appreciated!

**Comment by EmandM** [comment]
Unfortunately, `StepFunctions` is exported in a way that is incompatible with the `ImportMock` way of mocking out dependencies. `ImportMock` uses the module object as a stable point of reference in order to swap out real dependencies for fake dependencies. `StepFunctions` is exported as the module itself, leaving no stable point of reference for `ImportMock`.

You can work around this by putting these two lines in your code somewhere (e.g: `my-code/resources/aws/index.js`)
```javascript
import * as stepFunctionModule  from 'aws-sdk/clients/stepfunctions';
export class StepFunctions extends stepFunctionModule {}
```

You can then import `StepFunctions` using the module as a stable point of reference:

Production Code
```javascript
import { StepFunctions } from 'my-code/resources/aws';
const step = new StepFunctions({ region: config.aws_region });
```

Tests
```javascript
import  *  as stepFunctionModule from 'my-code/resources/aws';

describe('', function() {
   let stepFunctionMock;
   before(function () {
     stepFunctionMock = Import.mockClass(stepFunctionModule, 'StepFunctions');
   });
});
```

Everything should now work as expected.

**Comment by lsanders** [comment]
(Note, this isn't directly related to this library, but adding to this discussion in case someone with the same problem lands here)

@EmandM This worked really well, until I deployed. After webpacking, the production code throws:

`TypeError: Class constructor  cannot be invoked without 'new'` when accessing the extended class. Googling suggests this is a problem with transpiling. We're using serverless with serverless-plugin-typescript and serverless-webpack plugins. The webpack config is pretty basic (although I don't know what serverless-webpack might add).

Any pointers are appreciated!

**Comment by EmandM** [comment]
After looking through the aws library further, I've found a more complete solution. You can also import `StepFunctions` from `'aws-sdk/clients/all'`

Therefore your code becomes:

Production Code
```javascript
import { StepFunctions } from 'aws-sdk/clients/all';
```

Tests
```javascript
import * as awsClient from 'aws-sdk/clients/all';

describe('', function() {
   let stepFunctionMock;
   before(function () {
     stepFunctionMock = Import.mockClass(awsClient , 'StepFunctions');
   });
});
```
This solution shouldn't have any problems compiling

**Comment by lsanders** [comment]
That works perfectly - can't believe it was that simple. Thanks for all your help!
