### ISSUE TITLE
Cannot mock static methods of a class

### ISSUE THREAD

**Issue by sambeckett303** [EmandM/ts-mock-imports#15]
Hello,

I'm trying to write a test, and I need to mock out a class. The (simplified) class I need to mock looks something like:

```
export class MyClass {
  private services: any;
  private static instance: MyClass;

  private constructor() {
    this.services = {};
    return MyClass.instance;
  }

  public static getInstance() {
    if( !MyClass.instance ) {
      MyClass.instance = new MyClass();
    }
    return MyClass.instance;
  }

 .. more functions ..
}
```

Then how this class is used in the module I'm writing a test for:
```
Import { MyClass } from 'path/to/class'

let service = MyClass.getInstance().get('someservice').service
```

So I try to mock this out like so:
```
import { ImportMock, MockManager } from 'ts-mock-imports';
import * as myClassModule from 'path/to/class';

describe('Test Activity Controller', () => {
  let myClassMock: MockManager<myClassModule.MyClass>;

  before('set up mocks', (done) => {
    myClassMock = ImportMock.mockClass(myClassModule, 'MyClass')
    myClassMock.mock('getInstance', {});
    done()
  })
```

This will lead to a Typescript error: "Argument of type '"getInstance"' is not assignable to parameter of type '"get" | "register" | "unregister" | "cleanup"'.

"get", "register", "unregister", and "cleanup" are all non-static methods available to MyClass. I can mock these functions no problem.

I have tried to use the "mockStaticClass" function, but this doesn't seem to help. I've also tried to use the "mockOther" class, but this is requiring that I build up an object that has the exact same signature as the class that I'm mocking , and this is proving to be tedious.

Has anyone come across this situation before..?

**Comment by EmandM** [comment]
What issues do you get when using mockStaticClass?

**Comment by sambeckett303** [comment]
@EmandM  If I use mockStaticClass, I get the same Typescript error as mentioned in the post above. One thing I should probably mention is the class I am mocking is not a static class, it just has a static method.

**Comment by EmandM** [comment]
Are you getting the same error for the same function?

Note that when you use `mockStaticClass`, you need to ensure that
```
let myClassMock: MockManager<myClassModule.MyClass>;
```
changes to:
```
let myClassMock: StaticMockManager<myClassModule.MyClass>;
```

Can you let me know what error occurs when you use `mockStaticClass` and `StaticMockManager`?

**Comment by EmandM** [comment]
It doesn't matter whether it's a full static class or not, the separation is simply there as the typing works differently for static methods vs instance methods.

**Comment by sambeckett303** [comment]
Hey Emma,

Thanks for the response! I must've been missing something on my original implementation. Maybe I didn't have the correct type.

I have tried it again with your updated suggestions and now it seems to be working fine for me, allowing me to mock out the static methods. 

Thanks again and sorry!

**Comment by EmandM** [comment]
No problem. Glad it was resolved
