### ISSUE TITLE
Add "How To Expect Something Was Called With The Correct Args" To README docs?

### ISSUE THREAD

**Issue by JimLynchCodes** [EmandM/ts-mock-imports#18]
Hi, I am just thinking that for any mocked function called by the function under test, you could have an assertion checking that the mocked function was called with the proper arguments based on the other inputs passed into the FUT...

I'm guessing the solution is probably just regular sinon syntax, but I think it would still help newcomers to have a simple example there in the docs! 🙂

**Comment by EmandM** [comment]
As this is a Typescript library, it is assumed that if the code compiles, the function was called with all the correct types.

This library is designed for mocking out dependencies during test run time, it was not intended as a replacement for sinon. If you would like more detailed sinon functionality, feel free to create an issue in the sinon repo.
