### ISSUE TITLE
Mocking superclass

### ISSUE THREAD

**Issue by jayalakshmi-rm** [EmandM/ts-mock-imports#2]
**Is there any way to mock superclass call.** *Kindly consider the below scenario to resolve to mock*

```javascript
export default class DefaultClass extends TestClass {
  testData: string;
  constructor(a: string, b: string) {
    this.testData = a + ' '+ b + ' data';
  }
}


import { TestClass } from './test-class';

export default class DefaultClass extends TestClass {
  constructor(a: string) {
    super(a, 'default class');
  }

  foo() {
    return this.testData;
  }
}

import DefaultClass from './default-class';

export class DefaultClassConsumer extends  DefaultClass{
  private testClass: testDefaultExport;
  constructor() {
    super('Consumer');
  }

  public consumerCall() {
    return this.foo(); // Returns "Consumer default class data"
  }
}
```

*Here am testing **DefaultClassConsumer** class using ts-mock-imports and the parent class constructor is called by super method. Because of this I couldnt create a object for "DefaultClassConsumer" Let me know is there any solution for this* :+1:

**Comment by EmandM** [comment]
What is your expected behaviour from ts-mock-imports? Is it throwing an error or just not working how you anticipate? Do you mind posting your test code?

**Comment by jayalakshmi-rm** [comment]
I cant update my test code here. I'll explain you my scenario.

I am testing **DefaultClassConsumer** so I have mocked super DefaultClass class using **mockClass** to avoid constructor call.

Then I created object for 
Let dftConsumer = new DefaultClass();
Above code is executing super class constructor and its throwing error because of super class dependencies. 

The proper solution would be avoiding the super class constructor call. But as a work around now I mocked super class dependencies also.

Thanks for your response Emand. It will be useful if we have any solution other than mocking super class dependencies.

Thanks,
Jayalakshmi RM

**Comment by EmandM** [comment]
Unfortunately you cannot change the behavior of the constructor without mocking the entire class at this point. There might be potential to add a `mockConstructor` function, but mocking all dependencies (including super dependencies) of the code under test is the correct solution.
