### ISSUE TITLE
Sinon sandbox-like functionality

### ISSUE THREAD

**Issue by Snepsts** [EmandM/ts-mock-imports#20]
Hi, I like this library a lot! It works great for us to mimic how we tested things in Javascript. It is particularly useful in converting our old JS with CommonJS tests to new TS with ES6 imports.

There is just one thing that feels like it is missing, and that is something to mimic this behavior:

```javascript
const sinon = require('sinon');
const genericService = require('./generic-service');

describe('generic-service', () => {
  const sandbox = sinon.createSandbox();

  afterEach(() => {
    sandbox.restore();
  });

  describe('genericServiceFunction', () => {
    it('should successfully execute the function.', async () => {
      const startJobStub = sandbox.stub(genericService, 'startJob')
        .resolves({job: {id: '123'}});
      const checkJobStub = sandbox.stub(genericService, 'checkJob')
        .resolves({job: {id: '123', status: 'inProgress'}});

      await genericService.genericServiceFunction();

      sinon.assert.calledOnce(startJobStub);
      sinon.assert.calledOnce(checkJobStub);
    });
  });
});
```

Basically, I want to be able to tie all of the stubs to an object and be able to `restore` all of them at once (much like how sinon.sandbox works). It makes tests a lot cleaner to write when you can leave all the `.restore()`s out in favor of one that gets called in the `afterEach` instead.

I can do the work required for this if necessary, but I wanted to make an issue to track or see if this functionality exists in some capacity already and I just missed it.

Thanks!

**Comment by EmandM** [comment]
After sinon 5.0, the entire sinon object is a sandbox. So rather than manually creating individual sandboxes, you can call restore on the sinon object itself. [(More info here)](https://sinonjs.org/guides/migrating-to-5.0.html)

I can see how having a universal restore is a useful use-case. Happy to implement that for this library. I think it is cleaner and easier to implement `ImportMock.restore()` rather than following the `createSandbox()` syntax however.

**Comment by Snepsts** [comment]
Oh that's cool, did not know that.

Yeah I assumed it wouldn't be a `createSandbox()` syntax, but something that builds off of the existing functionality. Thank you for considering!

**Comment by EmandM** [comment]
Release v1.3.0 now has this functionality. Thanks for recommending it!
