### ISSUE TITLE
How to mock default methods?

### ISSUE THREAD

**Issue by arboleya** [EmandM/ts-mock-imports#23]
Hi, thanks for such a library. I loved it!

How should I mock default methods (not classes), like this one below?

```ts
// notify.ts
import needle from 'needle'

// want to mock the `needle` default method

export const notify = async () => {
   return needle( /* ... */ )
}
```

I was first trying just like the others, but it doesn't work:

```ts
// notify.test.ts

import { notify } from './notify'

import * as needleMod from 'needle'
import { ImportMock } from 'ts-mock-imports'


describe(`mock default`, () => {


  it('should mock default', async () => {
    
    const pYes = Promise.resolve(true)
    const needleDefault = m(needleMod, 'default', pYes)

    await notify()

    expect(needleDefault.callCount).to.eq(1) // never called, always = 0

  })

})

```

I have tried other combinations as per the readme, but without any luck.

Thanks.

**Comment by EmandM** [comment]
Can you provide more information about `needle` and `notify`. The way you are mocking default is correct and should work, so more information about how `needle` is exported and imported is needed.

**Comment by arboleya** [comment]
@EmandM I did more tests with it and it indeed works as expected. The problem, I believe, is that my dependency defines its `exports` inside conditionals.
