### ISSUE TITLE
How to check parameters of mocked instance

### ISSUE THREAD

**Issue by IgniparousTempest** [EmandM/ts-mock-imports#25]
Assuming we have `service.ts`:
```typescript
declare class Service {
    /**
     * Override this method to setup any custom request listeners for each new request to the service.
     */
    setupRequestListeners(request: RequestType): void;
}
export = Service;
```

A file, `foo.ts` that uses it:

```typescript
import Service from './service';

function baz() {
    const bar = new Service();
    bar.setupRequestListeners = (request: RequestType) => {
        ...
    }
}
```

A file, `foo.spec.ts` that tests `foo.ts` it:

```typescript
import * as ServiceImport from './service';
import { baz } from './foo';

describe('foo', () => {
    const serviceImportMock = ImportMock.mockClass(ServiceImport);
    baz();
    const mock = serviceImportMock.getMockInstance();  // This doesn't seem to return the mocked instance.
    expect(mock.setupRequestListeners).to.equal(...);
}
```

I would like to access the instanciated mock in my tests and test parameters on it. How do I do that? Calling `.getMockInstance()` doesn't seem to give me the instance.

**Comment by EmandM** [comment]
`.getMockInstance()` will give you *an* instance of the mock, not necessarily the instance that your code is using. There's no real way to get that, as it's your code that creates the mock instance. I'd have to know more about your underlying code to see what you're attempting to test here.
