### ISSUE TITLE
Where can I send you a beer?

### ISSUE THREAD

**Issue by karltaylor** [EmandM/ts-mock-imports#27]
![https://media3.giphy.com/media/IcGkqdUmYLFGE/giphy.gif?cid=ecf05e475c63796c71eb19ba2fad8b115e30aaea587e59c1&rid=giphy.gif](https://media3.giphy.com/media/IcGkqdUmYLFGE/giphy.gif?cid=ecf05e475c63796c71eb19ba2fad8b115e30aaea587e59c1&rid=giphy.gif)

**Comment by EmandM** [comment]
Thank you! Just glad this library was able to help
