### ISSUE TITLE
sinon dependency not properly listed

### ISSUE THREAD

**Issue by jason-ha** [EmandM/ts-mock-imports#39]
`package.json` lists `sinon` as `devDependency,` but the package does not function without `sinon` as an [implementation] `dependency`.

When adding `ts-mock-imports` as a `devDependency`, `sinon` will not be installed. Attempting to run in such a state produces:
```
Error: Cannot find module 'sinon'
Require stack:
- ...\node_modules\ts-mock-imports\lib\import-mock.js
- ...\node_modules\ts-mock-imports\lib\index.js
- MyStuff.unit.tests.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (...\node_modules\ts-mock-imports\src\import-mock.ts:1:1)
```

Temporary workaround is to also add `sinon` dependency whenever `ts-mock-imports` is added, but shouldn't have to do that.

**Comment by EmandM** [comment]
Sinon is listed as `peerDependency`. This means `ts-mock-inputs` will use whatever version of `sinon` is currently in the project, rather than installing its own version. More info here https://nodejs.org/es/blog/npm/peer-dependencies/. A warning should be generated saying that `sinon` is required on `npm install`.

The `sinon` that is listed in `devDependencies` is there so `sinon` exists while developers are working on the `ts-mock-inputs` package itself.

**Comment by jason-ha** [comment]
However, ts-mock-imports is not a _plug-in_ and **requires** sinon. Peer dependencies are good for model where there isn't a direct dependency. For example, ts-mock-imports is given sinon objects/functions to use. 
From https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies:
> In some cases, you want to express the compatibility of your package with a host tool or library, while not necessarily doing a `require` of this host.

Other useful posts on this topic:
[The problem peer dependencies solve - stackoverflow.com](https://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins/34645112#34645112)
[Understanding and managing peer dependencies in your project](https://piraces.dev/posts/understanding-and-managing-peer-dependencies/) (good explanation about conflicts which is not the issue here)

It would be okay for the users of sinon to deduplicate sinon on their install set or for sinon to be duplicated.

For sure dependency management and expression is complicated. :)
Please reconsider using a more correct dependency listing.

**Comment by EmandM** [comment]
The design behind `ts-mock-imports` envisages sinon being used for most of the mocking, and `ts-mock-imports` handling only the import swap piece. Therefore it is assumed that users are creating their own sinon objects, alongside the objects returned by `ts-mock-imports`.

The `manager.mock...()` functions return `sinonStub` objects directly, exposing the sinon dependency to the user. When sinon is a peer dependency, the sinon object that is returned will be the same version and have the same features as other sinon objects in the test suite. With sinon as a direct dependency you do not have that guarantee, and this will lead to a typing (and implementation) nightmare.

**Comment by jason-ha** [comment]
Not being `sinon` experienced and just trying to go by APIs documented in the two packages, I would guess that there isn't a complication with "creating their own `sinon` objects, alongside the objects returned by `ts-mock-imports`" as there won't be interaction between stubs. However, I will defer to your expertise.

It does seem that with `ts-mock-imports` being really on top it would be nice to require `sinon` be passed in. If the sandbox were passed in, that would be very clear and convenient (at least from my novice understanding). But it would not be as "pretty". I suppose the best form is to have this support incorporated into `sinon` directly. At the same time, it is good to be able to have help libraries like this.

We haven't been able to move beyond npm 6. I suppose this became more common variant of the "plug-in issue" enough for npm to change back to making peers auto install, when meta data doesn't say optional.

To answer your question about warning by npm, we don't see that. The repo in question is a mono repo using lerna and those warnings apparently don't come through. Someone even wrote a helper script to find missing peer dependencies, but for some reason it also doesn't reveal this one. Maybe it is skipping devDependencies.

I am fully accepting this as Closed with no change. I will look forward to moving to npm 7+ and then will remove what appears as unused `sinon` in package devDependencies. Thanks for your time.

**Comment by EmandM** [comment]
If you are talking about the `sinon` that's listed as a devDependency on this package, that is not an unused dependency. It is there for when developers are working on this package and need to install dependencies in order to test.

I'm glad that the latest version of Node will fix this issue for you.

**Comment by jason-ha** [comment]
Not really saying anything about `sinon` `devDependency` in `ts-mock-imports`. (The first post should have said `peerDependency` rather than `devDependency`.) In my most recent post, where I mentioned "devDependency", I was talking about the dev dependencies in the project depending on `ts-mock-imports`. It is possible that the helper script in use is not paying attention to peer dependencies of local dev dependencies.
