### ISSUE TITLE
First example in README has confusing bugs

### ISSUE THREAD

**Issue by hallvors** [EmandM/ts-mock-imports#78]
This is the first example of a test script in the README:

```
import { ImportMock } from 'ts-mock-imports';
import { Bar } from './Bar';
import * as fooModule from '../src/foo';

// Throws error
const bar = new Bar();

const mockManager = ImportMock.mockClass(fooModule, 'Foo');

// No longer throws an error
const bar = new Bar();

// Easily add mock responses for testing
mockmanager.mock('getCount', 3)

// Call restore to reset all mocked objects to original imports
ImportMock.restore();
```

1. Looking at the snippets just above, I think 
`import { Bar } from './Bar';` should be `import { Bar } from '../src/bar';`

2. The case here does not match the case where `mockManager` is declared:  `mockmanager.mock('getCount', 3)`

**Comment by EmandM** [comment]
Thank you for pointing this out. The README should now be updated with a consistent example filesystem.

**Comment by hallvors** [comment]
Thank you for fixing! 👍 

You may also want to fix the case of `M` in the variable name to be consistent in the example here:
<img width="498" alt="Skjermbilde 2024-12-11 kl  22 13 51" src="https://github.com/user-attachments/assets/ff42046f-4a36-4423-a93a-d4ba40e146b6" />
