### ISSUE TITLE
Doesn't appear to be published correctly

### ISSUE THREAD

**Issue by dav-is** [EmandM/ts-mock-imports#8]
https://github.com/EmandM/ts-mock-imports/blob/b1cad17a8fa8f7f9fd9bdf99d9b5723efdfd53ae/package.json#L3
https://github.com/EmandM/ts-mock-imports/blob/b1cad17a8fa8f7f9fd9bdf99d9b5723efdfd53ae/package.json#L31

```
warning " > ts-mock-imports@1.2.2" has incorrect peer dependency "typescript@>=2.6.1 < 3.2".
```

Inside `./node_modules/ts-mock-imports/package.json`:
```
{
  ...
  "version": "1.2.2",
  ...
  "peerDependencies": {
    "typescript": ">=2.6.1 < 3.2",
    "sinon": ">= 4.1.2 < 7"
  },
  ...
}
```

**Comment by EmandM** [comment]
A new version has now been published.
